name: CI on-push
on:
  push:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update system
        run: sudo apt-get update
      - name: Export envs
        run: export TERM="headless"
      - name: Install libs
        run:  sudo apt-get install -y flex bison libfl-dev libmpc-dev
      - name: Install tools
        run:  sudo apt-get install -y lld clang xorriso mtools nasm
      - name: Bootstrap project
        run: ./bootstrap
      - name: Configure project
        run: ./configure
      - name: Build toolchain
        run: make toolchain
      - name: Build system
        run: make
